#!/usr/bin/env bash
# codex_minimax_config.sh — write the official MiniMax provider config
# into ~/.codex/config.toml when MINIMAX_API_KEY is set. Sourced by
# start.sh (Docker boot) and the bare-host install path so both get
# the same shape.
#
# Source: https://platform.minimax.io/docs/token-plan/codex-cli
#
# WIRE_API CONTRACT (codex CLI 0.130, baked by #219 — internal#513):
# codex CLI 0.130 REMOVED the `chat` WireApi variant entirely (the
# OpenAI Chat Completions wire was dropped fleet-wide in Feb 2026,
# https://github.com/openai/codex/discussions/7782). 0.130 hard-fails
# config.toml parsing with
#   `wire_api = "chat"` is no longer supported. set `wire_api = "responses"`
# at the line that holds it — BEFORE auth.json / OPENAI_API_KEY is even
# read. So `chat` is invalid UNCONDITIONALLY for every provider block
# under 0.130; it is no longer a per-provider choice. We therefore emit
# `wire_api = "responses"` (the only parse-valid value on this CLI).
#
# PROD IMPACT: the production codex agents (Reviewer/Researcher) run the
# ChatGPT/Codex *subscription* OAuth path (CODEX_AUTH_JSON → ~/.codex/
# auth.json, model gpt-5.5). That is the OpenAI provider, which natively
# requires the Responses API on 0.130 — so `responses` is exactly
# correct for the path prod actually uses.
#
# KNOWN MINIMAX LIMITATION (documented, out of scope for internal#513):
# MiniMax's token-plan endpoint (https://api.minimax.io/v1) is an
# OpenAI *Chat Completions*-compatible API; per MiniMax's own codex-cli
# docs it does NOT serve the OpenAI Responses API. With `chat` removed
# from the CLI there is no parse-valid wire that MiniMax natively
# accepts on 0.130 — the MiniMax token-plan route needs its own
# follow-up (a Responses→Chat translation shim, or MiniMax shipping
# Responses support). We still write `responses` here so the config
# PARSES (the alternative is a non-loadable config that bricks every
# boot, incl. the subscription path). This is acceptable because no
# prod agent uses the MiniMax leg today (subscription is `Preferred`
# per README; OPENAI_API_KEY is the documented fallback) — both of
# those are native Responses providers. Tracked: molecule-ai/internal#514
# ("codex MiniMax token-plan leg incompatible with CLI 0.130 Responses-API,
# deferred from #513") — the dedicated follow-up for the MiniMax-Responses
# gap; internal#513 remains this change's cutover-blocker.
#
# When MINIMAX_API_KEY is missing this is a no-op so OpenAI-direct
# users see no behavior change.

set -euo pipefail

if [ -z "${MINIMAX_API_KEY:-}" ]; then
  echo "[codex-minimax] no MINIMAX_API_KEY — codex will use its default (OpenAI) provider"
  return 0 2>/dev/null || exit 0
fi

CODEX_HOME="${CODEX_HOME:-${HOME}/.codex}"
mkdir -p "$CODEX_HOME"
CONFIG_TOML="${CODEX_HOME}/config.toml"

# Defaults pulled from MiniMax's official Codex CLI config
# (https://platform.minimax.io/docs/token-plan/codex-cli). Operators
# can override the model via CODEX_MINIMAX_MODEL or the base_url via
# MINIMAX_API_BASE (mainland-China ingress is api.minimaxi.com/v1).
MODEL="${CODEX_MINIMAX_MODEL:-codex-MiniMax-M2.7}"
BASE_URL="${MINIMAX_API_BASE:-https://api.minimax.io/v1}"

cat > "$CONFIG_TOML" <<EOF
# Auto-generated by codex_minimax_config.sh — do not edit by hand;
# regenerated on every boot from MINIMAX_API_KEY / CODEX_MINIMAX_MODEL
# / MINIMAX_API_BASE env. Source: MiniMax docs (token-plan/codex-cli).
model = "${MODEL}"
model_provider = "minimax"

[model_providers.minimax]
name = "MiniMax Chat Completions API"
base_url = "${BASE_URL}"
env_key = "MINIMAX_API_KEY"
# codex CLI 0.130 removed the `chat` WireApi variant — `responses` is
# the only parse-valid value (internal#513). See header note for the
# known MiniMax-Responses limitation; this keeps config.toml loadable
# so the subscription/OpenAI paths boot. DO NOT revert to "chat": CLI
# 0.130 hard-fails config parse at this exact line and the codex agent
# loop never starts (the live A2A blocker on prod-Reviewer/Researcher).
wire_api = "responses"
requires_openai_auth = false
request_max_retries = 4
stream_max_retries = 10
stream_idle_timeout_ms = 300000
EOF

# Inherit ownership from the codex home dir so the agent user (which
# runs molecule-runtime) can read it under gosu.
if command -v stat >/dev/null 2>&1; then
  owner=$(stat -c "%u:%g" "$CODEX_HOME" 2>/dev/null || echo "")
  if [ -n "$owner" ]; then
    chown "$owner" "$CONFIG_TOML" 2>/dev/null || true
  fi
fi

echo "[codex-minimax] wrote ${CONFIG_TOML} model=${MODEL} provider=minimax"

# Also patch /configs/config.yaml so molecule-runtime's load_config()
# passes ${MODEL} to executor.py instead of the library default
# (anthropic:claude-opus-4-7), which codex CLI rejects with
# `unknown model 'anthropic:claude-opus-4-7' (2013)` and hangs the
# first turn until task_complete that never arrives. Caught live on
# the 4-runtime A2A E2E (2026-05-03): codex executor took the turn
# lock, called turn/start with the wrong model, and never released
# — every subsequent A2A request piled up in the workspace-server
# queue as "busy".
#
# The provisioner has a MODEL_PROVIDER pass-through (ec2.go:1923) but
# never exports it from user-data, so the only path for a runtime to
# get the right model is to patch config.yaml from the install-time
# context that knows about MINIMAX_API_KEY.
WORKSPACE_CONFIG_DIR="${WORKSPACE_CONFIG_PATH:-/configs}"
WORKSPACE_CONFIG="${WORKSPACE_CONFIG_DIR}/config.yaml"
if [ -f "$WORKSPACE_CONFIG" ] && [ -w "$WORKSPACE_CONFIG_DIR" ]; then
  if grep -qE '^model:' "$WORKSPACE_CONFIG"; then
    sed -i.bak "s|^model: .*|model: '${MODEL}'|" "$WORKSPACE_CONFIG" && rm -f "${WORKSPACE_CONFIG}.bak"
  else
    printf "model: '%s'\n" "$MODEL" >> "$WORKSPACE_CONFIG"
  fi
  echo "[codex-minimax] patched ${WORKSPACE_CONFIG} model=${MODEL}"
elif [ -f "$WORKSPACE_CONFIG" ]; then
  # Read-only mount or wrong owner — log so operators can debug
  # rather than silently shipping the wrong default model.
  echo "[codex-minimax] WARN: ${WORKSPACE_CONFIG} exists but ${WORKSPACE_CONFIG_DIR} not writable; runtime will use default model" >&2
fi
